nelmio_api_doc:
    documentation:
        info:
            title: Maule player
            description: Media AUdio Library Experience
            version: 1.0.0
        components:
            schemas:
                Error:
                    type: object
                    properties:
                        errorMessage:
                            type: string
                    required: [errorMessage]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        disable_default_routes: true # Hide non-tagged routes (including doc.json route)
