nelmio_api_doc:
    documentation:
        info:
            title: Maule player
            description: Media AUdio Library Experience
            version: 1.0.0
        components:
            schemas:
                Error:
                    type: object
                    properties:
                        errorMessage:
                            type: string
                    required: [errorMessage]
    models:
        names:
            - {alias: Artist (full), type: App\Entity\Artist}
            - {alias: Album (full), type: App\Entity\Album}
            - {alias: Track (full), type: App\Entity\Track}
            - {alias: Artist (simplified), type: App\Entity\Artist, groups: [artist] }
            - {alias: Album (simplified), type: App\Entity\Album, groups: [album] }
            - {alias: Track (simplified), type: App\Entity\Track, groups: [track] }
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        disable_default_routes: true # Hide non-tagged routes (including doc.json route)
