# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app_locale: en|fr|transCode
    app_name: 'Maule player'
    app_version: '0.4.0'
    media_path_separator: '%env(MEDIA_PATH_SEPARATOR)%'
    # below parameter use previous parameter pathSeparator, bit complex to read ;)
    medialib_folder: '%kernel.project_dir%%media_path_separator%public%media_path_separator%media_lib%media_path_separator%'
    token_generator_secret: '%env(TOKEN_GENERATOR_SECRET)%'
    # email_sender: something@something.com
    user_passwords:
        maule_admin: '%env(USER_PASSWORD_MAULE_ADMIN)%'

keiwen_cacofony:
    token_generator:
        secret:               '%token_generator_secret%'
        # see openSSL allowed algo
        cipher_algo:          aes-128-cbc
        # have to be exactly 16-chars long
        openssl_iv:           KW-MAULE_init_iv

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Security\UserProvider:
        arguments:
            $userPlainPasswords: '%user_passwords%'

    App\Command\ImportTracksCommand:
        arguments:
            $medialibFolder: '%medialib_folder%'
            $pathSeparator : '%media_path_separator%'

    App\Command\DetectExtensionCommand:
        arguments:
            $medialibFolder: '%medialib_folder%'
            $pathSeparator : '%media_path_separator%'
